"""Remove content field from assignment_submissions

Revision ID: 2425bcde8275
Revises: d95387768446
Create Date: 2025-09-18 15:38:44.038655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2425bcde8275'
down_revision: Union[str, Sequence[str], None] = 'd95387768446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_submissions', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('content', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
