"""Re-add content column to submissions

Revision ID: 24d268ba3131
Revises: ce52d00bdb85
Create Date: 2025-09-18 16:41:08.359328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d268ba3131'
down_revision: Union[str, Sequence[str], None] = 'ce52d00bdb85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_submissions', 'content')
    # ### end Alembic commands ###
