"""Re-add content column to submissions with nullabe true

Revision ID: 5b185a12c6b4
Revises: 24d268ba3131
Create Date: 2025-09-18 16:55:54.263995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b185a12c6b4'
down_revision: Union[str, Sequence[str], None] = '24d268ba3131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_submissions', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('content', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
