"""Updating noc managemt part

Revision ID: 6e18de25242c
Revises: ce513e5a4d5a
Create Date: 2025-09-20 12:41:35.685535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e18de25242c'
down_revision: Union[str, Sequence[str], None] = 'ce513e5a4d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subject_status', sa.Column('final_status', sa.Enum('PENDING_VERIFICATION', 'GRANTED', 'REFUSED', name='nocfinalstatus'), nullable=False, server_default='PENDING_VERIFICATION'))
    op.drop_column('student_subject_status', 'is_noc_eligible')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subject_status', sa.Column('is_noc_eligible', sa.BOOLEAN(), nullable=True))
    op.drop_column('student_subject_status', 'final_status')
    # ### end Alembic commands ###
