"""noc seprate status update

Revision ID: 77023fb2161c
Revises: abf110c043c2
Create Date: 2025-09-21 10:42:18.326743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77023fb2161c'
down_revision: Union[str, Sequence[str], None] = 'abf110c043c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subject_status', sa.Column('theory_noc_status', sa.Enum('PENDING', 'COMPLETED', 'GRANTED', 'REFUSED', name='nocstatus'), nullable=False, server_default='PENDING'))
    op.add_column('student_subject_status', sa.Column('lab_tut_noc_status', sa.Enum('PENDING', 'COMPLETED', 'GRANTED', 'REFUSED', name='nocstatus'), nullable=False, server_default='PENDING'))
    op.drop_column('student_subject_status', 'noc_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subject_status', sa.Column('noc_status', sa.VARCHAR(length=9), server_default=sa.text("'PENDING'"), nullable=False))
    op.drop_column('student_subject_status', 'lab_tut_noc_status')
    op.drop_column('student_subject_status', 'theory_noc_status')
    # ### end Alembic commands ###
