"""Add lab and tutorial attendance columns

Revision ID: abf110c043c2
Revises: ebbfe9b16c5b
Create Date: 2025-09-20 23:21:25.796332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf110c043c2'
down_revision: Union[str, Sequence[str], None] = 'ebbfe9b16c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subject_status', sa.Column('lab_attendance_percentage', sa.Float(), nullable=True))
    op.add_column('student_subject_status', sa.Column('tutorial_attendance_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_subject_status', 'tutorial_attendance_percentage')
    op.drop_column('student_subject_status', 'lab_attendance_percentage')
    # ### end Alembic commands ###
