"""Replace tfidf with plagiarism fingerprint

Revision ID: ce513e5a4d5a
Revises: bb5674308da5
Create Date: 2025-09-19 17:47:15.672794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce513e5a4d5a'
down_revision: Union[str, Sequence[str], None] = 'bb5674308da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('plagiarism_fingerprint', sa.Text(), nullable=True))
    op.drop_column('assignment_submissions', 'tfidf_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('tfidf_vector', sa.TEXT(), nullable=True))
    op.drop_column('assignment_submissions', 'plagiarism_fingerprint')
    # ### end Alembic commands ###
