"""Updating noc managemt part 2

Revision ID: ebbfe9b16c5b
Revises: 6e18de25242c
Create Date: 2025-09-20 16:34:45.065760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbfe9b16c5b'
down_revision: Union[str, Sequence[str], None] = '6e18de25242c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subject_status', sa.Column('noc_status', sa.Enum('PENDING', 'COMPLETED', 'GRANTED', 'REFUSED', name='nocstatus'), nullable=False, server_default='PENDING'))
    op.add_column('student_subject_status', sa.Column('noc_reason', sa.String(), nullable=True))
    op.drop_column('student_subject_status', 'noc_ineligibility_reason')
    op.drop_column('student_subject_status', 'final_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subject_status', sa.Column('final_status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING_VERIFICATION'"), nullable=False))
    op.add_column('student_subject_status', sa.Column('noc_ineligibility_reason', sa.VARCHAR(), nullable=True))
    op.drop_column('student_subject_status', 'noc_reason')
    op.drop_column('student_subject_status', 'noc_status')
    # ### end Alembic commands ###
